const operatorData = [
    // ATTACKERS
    { name: "Montagne", role: "Attacker", weapons: [{ name: "P9", x: 1, y: 1 }] },
    { name: "Blitz", role: "Attacker", weapons: [{ name: "P12", x: 1, y: 2 }] },
    { name: "Dokkaebi", role: "Attacker", weapons: [{ name: "BOSG.12.2", x: 0, y: 5 }, { name: "Mk 14 EBR", x: -1, y: 15 }, { name: "SMG-12", x: 2, y: 10 }] },
    { name: "Kali", role: "Attacker", weapons: [{ name: "CSRX 300", x: 0, y: 1 }, { name: "SPSMG9", x: 1, y: 8 }] },
    { name: "Maverick", role: "Attacker", weapons: [{ name: "M4", x: 1, y: 6 }] },
    { name: "Deimos", role: "Attacker", weapons: [{ name: "Vendetta", x: 1, y: 7 }, { name: "AK-74M", x: -1, y: 11 }] },
    { name: "Blackbeard", role: "Attacker", weapons: [{ name: "MK17", x: 2, y: 8 }, { name: "SR-25", x: 0, y: 5 }] },
    { name: "Sledge", role: "Attacker", weapons: [{ name: "L85A2", x: 1, y: 10 }] },
    { name: "Thatcher", role: "Attacker", weapons: [{ name: "AR33", x: 1, y: 11 }, { name: "L85A2", x: 1, y: 9 }] },
    { name: "Thermite", role: "Attacker", weapons: [{ name: "556XI", x: 2, y: 10 }] },
    { name: "Nomad", role: "Attacker", weapons: [{ name: "ARX200", x: -1, y: 10 }, { name: "AK-74M", x: -1, y: 11 }] },
    { name: "Gridlock", role: "Attacker", weapons: [{ name: "F90", x: 0, y: 10 }, { name: "M249 SAW", x: 0, y: 12 }] },
    { name: "Brava", role: "Attacker", weapons: [{ name: "PARA-308", x: 0, y: 11 }] },
    { name: "Flores", role: "Attacker", weapons: [{ name: "AR33", x: 1, y: 11 }] },
    { name: "Lion", role: "Attacker", weapons: [{ name: "V308", x: 1, y: 11 }] },
    { name: "Grim", role: "Attacker", weapons: [{ name: "552 Commando", x: 1, y: 11 }] },
    { name: "IQ", role: "Attacker", weapons: [{ name: "552 Commando", x: 1, y: 11 }, { name: "AUG A2", x: 1, y: 14 }] },
    { name: "Osa", role: "Attacker", weapons: [{ name: "556XI", x: 0, y: 12 }, { name: "PDW9", x: 1, y: 8 }] },
    { name: "Ying", role: "Attacker", weapons: [{ name: "T-95 LSW", x: 1, y: 12 }] },
    { name: "Sens", role: "Attacker", weapons: [{ name: "POF-9", x: 1, y: 12 }] },
    { name: "Amaru", role: "Attacker", weapons: [{ name: "G8A1", x: -1, y: 13 }] },
    { name: "Striker", role: "Attacker", weapons: [{ name: "M4", x: 0, y: 11 }, { name: "M249", x: 1, y: 13 }] },
    { name: "Hibana", role: "Attacker", weapons: [{ name: "Type-89", x: 0, y: 14 }] },
    { name: "Fuze", role: "Attacker", weapons: [{ name: "AK-12", x: 0, y: 14 }] },
    { name: "Ace", role: "Attacker", weapons: [{ name: "AK-12", x: 0, y: 14 }] },
    { name: "Buck", role: "Attacker", weapons: [{ name: "C8-SFW", x: 1, y: 15 }] },
    { name: "Iana", role: "Attacker", weapons: [{ name: "ARX200", x: 1, y: 13 }, { name: "G36C", x: 1, y: 11 }] },
    { name: "Jackal", role: "Attacker", weapons: [{ name: "C7E", x: 1, y: 15 }, { name: "PDW9", x: 1, y: 8 }] },
    { name: "Finka", role: "Attacker", weapons: [{ name: "Spear .308", x: 0, y: 16 }] },
    { name: "Nokk", role: "Attacker", weapons: [{ name: "FMG-9", x: 1, y: 16 }] },
    { name: "Zero", role: "Attacker", weapons: [{ name: "SC3000K", x: 1, y: 16 }] },
    { name: "Ash", role: "Attacker", weapons: [{ name: "R4-C", x: 0, y: 18 }, { name: "G36C", x: 1, y: 11 }] },
    { name: "Ram", role: "Attacker", weapons: [{ name: "R4-C", x: 0, y: 18 }] },
    { name: "Twitch", role: "Attacker", weapons: [{ name: "F2", x: 0, y: 25 }] },

    // DEFENDERS
    { name: "Rook", role: "Defender", weapons: [{ name: "P9", x: 1, y: 1 }, { name: "MP5", x: 0, y: 13 }, { name: "P90", x: 0, y: 11 }] },
    { name: "Alibi", role: "Defender", weapons: [{ name: "ACS12", x: 1, y: 2 }, { name: "Mx4 Storm", x: 1, y: 6 }] },
    { name: "Azami", role: "Defender", weapons: [{ name: "ACS12", x: 1, y: 2 }, { name: "9x19VSN", x: 1, y: 5 }] },
    { name: "Maestro", role: "Defender", weapons: [{ name: "ACS12", x: 1, y: 2 }, { name: "ALDA 5.56", x: 1, y: 6 }] },
    { name: "Castle", role: "Defender", weapons: [{ name: "UMP45", x: 0, y: 3 }] },
    { name: "Pulse", role: "Defender", weapons: [{ name: "UMP45", x: 0, y: 3 }] },
    { name: "Tachanka", role: "Defender", weapons: [{ name: "DP27", x: 0, y: 3 }, { name: "9x19VSN", x: 1, y: 5 }] },
    { name: "Caveira", role: "Defender", weapons: [{ name: "M12", x: 1, y: 4 }, { name: "Luison", x: 1, y: 6 }] },
    { name: "Sentry", role: "Defender", weapons: [{ name: "Commando 9", x: 1, y: 4 }] },
    { name: "Kaid", role: "Defender", weapons: [{ name: "AUG A3", x: 1, y: 4 }, { name: "TCSG12", x: 1, y: 21 }] },
    { name: "Skopos", role: "Defender", weapons: [{ name: "PCX-33", x: 1, y: 4 }] },
    { name: "Aruni", role: "Defender", weapons: [{ name: "Mk 14 EBR", x: 0, y: 5 }, { name: "P10 RONI", x: 1, y: 6 }] },
    { name: "Clash", role: "Defender", weapons: [{ name: "SPSMG9", x: 1, y: 8 }, { name: "P-10C", x: 1, y: 3 }] },
    { name: "Kapkan", role: "Defender", weapons: [{ name: "9x19VSN", x: 1, y: 5 }] },
    { name: "Thorn", role: "Defender", weapons: [{ name: "UZK50GI", x: 1, y: 5 }] },
    { name: "Warden", role: "Defender", weapons: [{ name: "MPX", x: 1, y: 5 }] },
    { name: "Valkyrie", role: "Defender", weapons: [{ name: "MPX", x: 1, y: 5 }] },
    { name: "Wamai", role: "Defender", weapons: [{ name: "MP5K", x: 1, y: 6 }, { name: "AUG A2", x: 1, y: 14 }] },
    { name: "Tubarao", role: "Defender", weapons: [{ name: "MPX", x: 1, y: 5 }, { name: "AR-15.50", x: 1, y: 7 }] },
    { name: "Melusi", role: "Defender", weapons: [{ name: "MP5", x: 1, y: 5 }] },
    { name: "Mozzie", role: "Defender", weapons: [{ name: "Commando 9", x: 1, y: 5 }, { name: "P10 RONI", x: 1, y: 6 }] },
    { name: "Bandit", role: "Defender", weapons: [{ name: "MP7", x: 1, y: 6 }] },
    { name: "Fenrir", role: "Defender", weapons: [{ name: "MP7", x: 1, y: 6 }] },
    { name: "Lesion", role: "Defender", weapons: [{ name: "T-5 SMG", x: 1, y: 6 }] },
    { name: "Jager", role: "Defender", weapons: [{ name: "416-C", x: 1, y: 6 }] },
    { name: "Vigil", role: "Defender", weapons: [{ name: "K1A", x: 1, y: 6 }, { name: "SMG-12", x: 2, y: 10 }] },
    { name: "Solis", role: "Defender", weapons: [{ name: "P90", x: 1, y: 6 }] },
    { name: "Oryx", role: "Defender", weapons: [{ name: "T-5 SMG", x: 1, y: 6 }] },
    { name: "Thunderbird", role: "Defender", weapons: [{ name: "Spear .308", x: 1, y: 6 }] },
    { name: "Ela", role: "Defender", weapons: [{ name: "Scorpion EVO 3", x: 1, y: 7 }] },
    { name: "Mira", role: "Defender", weapons: [{ name: "Vector .45 ACP", x: 1, y: 7 }] },
    { name: "Smoke", role: "Defender", weapons: [{ name: "FMG-9", x: 1, y: 9 }, { name: "SMG-11", x: 1, y: 9 }] },
    { name: "Mute", role: "Defender", weapons: [{ name: "MP5K", x: 1, y: 6 }, { name: "SMG-11", x: 1, y: 9 }] },
    { name: "Frost", role: "Defender", weapons: [{ name: "9mm C1", x: 0, y: 10 }] },
    { name: "Echo", role: "Defender", weapons: [{ name: "SuperNova", x: 1, y: 10 }, { name: "MP5SD", x: 1, y: 12 }] },
    { name: "Doc", role: "Defender", weapons: [{ name: "MP5", x: 0, y: 13 }, { name: "P90", x: 0, y: 11 }, { name: "Bailiff 410", x: 0, y: 17 }] },
    { name: "Goyo", role: "Defender", weapons: [{ name: "Vector .45 ACP", x: 0, y: 19 }] }
];
